# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  tags:
    include:
      - '*'

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'New-Item -Type Directory releasenotes; Get-Content CHANGELOG.md -Delimiter ''# '' | Select-String -List -Pattern "v\d*.\d*.\d" | Select -First 1 | %{ $_.ToString().Trim() | Out-File -FilePath releasenotes/RELEASE-$($_.Matches).md }'
    pwsh: true

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)'
    artifact: 'drop'
    publishLocation: 'pipeline'
