# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  tags:
    include:
      - '*'

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: PowerShell@2
  displayName: "Generate release notes"
  inputs:
    targetType: 'inline'
    # The following script will generate release notes in the releasenotes workingDirectory
    # based on the CHANGELOG.md file and the section between the first and second matched results
    # matching the pattern [v1.0.0]. Additionally, it will use the pattern as the postfix
    # for the release notes. These release notes will then be used in the 'Releases' pipeline
    # when editing the release/tag entry on Github. (i.e. RELEASE-v1.0.1.md).
    # EXAMPLE:
    #
    #  NOT INCLUDED
    #
    #  [v1.0.1] NOT INCLUDED
    #  THIS WILL BE INCLUDED IN THE RELEASE NOTES
    #  [v1.0.0] NOT INCLUDED
    #
    script: '
      New-Item -Type Directory -Path releasenotes -Force | Out-Null;
      $pattern = "\[v\d+\.\d+\.\d+\]";
      $content = Get-Content -Path ./CHANGELOG.md;
      $startLine = $content | Select-String -Pattern $pattern | Select -First 1 -ExpandProperty LineNumber;
      $endLine = $content | Select-String -Pattern $pattern | Select -Skip 1 -First 1 -ExpandProperty LineNumber;
      $postfix = $content | Select-Object -Skip ($startLine - 1) -First 1 | Select-String -Pattern "v\d+\.\d+\.\d+";
      $content | Select-Object -Index (($startLine + 1)..($endLine - 2)) | Out-File -FilePath "releasenotes/RELEASE-$($postfix.Matches.Value).md";
    '
    pwsh: true

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)'
    artifact: 'drop'
    publishLocation: 'pipeline'
